Updated readme to reflect changes
cryptic-game/gamedesign pull request #77
Opened 2020-06-28 17:48 UTC by TheDrakonir

**Description**
Updated readme to comply with the changes made to the German game design definition document.

**Issue**
Closes #76 

**Additional Notes**
The changes of the pull request should be spellchecked and crossread before merging.

2020-07-06 17:08 UTC, andyRonck commented
hi

2020-07-06 17:11 UTC, JannikEmmerich requested changes
Change commit message to `Updated readme to reflect changes (#76)`

2020-07-06 17:45 UTC, JannikEmmerich approved these changes

2020-08-15 17:16 UTC, DevMimas approved these changes

2020-09-07 15:37 UTC, andyRonck approved these changes

2020-09-20 11:38 UTC, merged